### ISSUE TITLE
Waila errors out when looking at TFC large vessels, spamming in cascade

### ISSUE THREAD

**Issue by wolfsilver00** [Verph/TerraFirmaCraft-Reloaded-2#4]
Recreate: place large vessel, look at it.

**Comment by Verph** [comment]
I highly doubt that's anything I can fix on my behalf. I apologize. In the mean time you can probably toggle Waila in-game, if you don't want error messages to show.

**Comment by Aiva418** [comment]
I submitted a bug report to the TFC GitHub. The issue should be fixed in their next release.

**Comment by wolfsilver00** [comment]
Awesome.. For now, instead of removing waila completely, another quick fix is to put vanillafix notifications to last 0 seconds and true on replace.. :)

**Comment by Aiva418** [comment]
That works, if you don't mind filling your crash reports folder with spam. I just downloaded the TFC repository and made a dev build for personal use until they push out another update.
